// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/matching.proto

package matchingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Order) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type PathCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathId        string                 `protobuf:"bytes,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathCandidate) Reset() {
	*x = PathCandidate{}
	mi := &file_proto_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathCandidate) ProtoMessage() {}

func (x *PathCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathCandidate.ProtoReflect.Descriptor instead.
func (*PathCandidate) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{1}
}

func (x *PathCandidate) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

type SelectBestPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Candidates    []*PathCandidate       `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectBestPathRequest) Reset() {
	*x = SelectBestPathRequest{}
	mi := &file_proto_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectBestPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBestPathRequest) ProtoMessage() {}

func (x *SelectBestPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBestPathRequest.ProtoReflect.Descriptor instead.
func (*SelectBestPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{2}
}

func (x *SelectBestPathRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SelectBestPathRequest) GetCandidates() []*PathCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SelectBestPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestPathId    string                 `protobuf:"bytes,1,opt,name=best_path_id,json=bestPathId,proto3" json:"best_path_id,omitempty"`
	EstimatedCost int32                  `protobuf:"varint,2,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectBestPathResponse) Reset() {
	*x = SelectBestPathResponse{}
	mi := &file_proto_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectBestPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBestPathResponse) ProtoMessage() {}

func (x *SelectBestPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBestPathResponse.ProtoReflect.Descriptor instead.
func (*SelectBestPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{3}
}

func (x *SelectBestPathResponse) GetBestPathId() string {
	if x != nil {
		return x.BestPathId
	}
	return ""
}

func (x *SelectBestPathResponse) GetEstimatedCost() int32 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

var File_proto_matching_proto protoreflect.FileDescriptor

const file_proto_matching_proto_rawDesc = "" +
	"\n" +
	"\x14proto/matching.proto\x12\bmatching\";\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\"(\n" +
	"\rPathCandidate\x12\x17\n" +
	"\apath_id\x18\x01 \x01(\tR\x06pathId\"w\n" +
	"\x15SelectBestPathRequest\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.matching.OrderR\x05order\x127\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x17.matching.PathCandidateR\n" +
	"candidates\"a\n" +
	"\x16SelectBestPathResponse\x12 \n" +
	"\fbest_path_id\x18\x01 \x01(\tR\n" +
	"bestPathId\x12%\n" +
	"\x0eestimated_cost\x18\x02 \x01(\x05R\restimatedCost2f\n" +
	"\x0fMatchingService\x12S\n" +
	"\x0eSelectBestPath\x12\x1f.matching.SelectBestPathRequest\x1a .matching.SelectBestPathResponseB/Z-DeliveryGO/internal/transport/grpc/matchingpbb\x06proto3"

var (
	file_proto_matching_proto_rawDescOnce sync.Once
	file_proto_matching_proto_rawDescData []byte
)

func file_proto_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)))
	})
	return file_proto_matching_proto_rawDescData
}

var file_proto_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_matching_proto_goTypes = []any{
	(*Order)(nil),                  // 0: matching.Order
	(*PathCandidate)(nil),          // 1: matching.PathCandidate
	(*SelectBestPathRequest)(nil),  // 2: matching.SelectBestPathRequest
	(*SelectBestPathResponse)(nil), // 3: matching.SelectBestPathResponse
}
var file_proto_matching_proto_depIdxs = []int32{
	0, // 0: matching.SelectBestPathRequest.order:type_name -> matching.Order
	1, // 1: matching.SelectBestPathRequest.candidates:type_name -> matching.PathCandidate
	2, // 2: matching.MatchingService.SelectBestPath:input_type -> matching.SelectBestPathRequest
	3, // 3: matching.MatchingService.SelectBestPath:output_type -> matching.SelectBestPathResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_matching_proto_init() }
func file_proto_matching_proto_init() {
	if File_proto_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_proto = out.File
	file_proto_matching_proto_goTypes = nil
	file_proto_matching_proto_depIdxs = nil
}
